config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'

  get  '/roomlist',    to: 'static_pages#roomlist'
  get  '/post',        to: 'static_pages#post'
  get  '/dashboard',   to: 'static_pages#dashboard'
  get  '/signup',      to: 'users#new'
  get  '/login',       to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  # resources :users #user作成のための7つのURL群を一度に作ってくれる
  # URLが別でも同じページを作成するようにできる。
  resources :account_activations, only: [:edit]
  # アカウント有効化のためのルーティング
  # 7つのアクションの中でのeditだけ作っている。
  # GET /account_activation/<token>/edit
  # tokenの部分に情報が入る。アクセスしたらedit（更新）アクションがはじまる。
  resources :password_resets,     only: %i[new create edit update]
  resources :microposts,          only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "つなリズム", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul id="navbar-menu" 
          class="nav navbar-nav navbar-right collapse navbar-collapse">
          
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "ルーム一覧・作成", roomlist_path %></li> 
        <li><%= link_to "ダッシュボード", dashboard_path %></li>        
        <li><%= link_to "投稿", post_path %></li> 
        <li><%= link_to "ユーザー", users_path  %></li>
          <li class="dropdown"> 
            <a href="#" id="account" class="dropdown-toggle">
              設定 <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path,
                                       data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li> 
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>